baseURL = "https://jiaoshijie.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Blog"
theme = "PaperMod"
publishDir = "/home/jsj/Downloads/Site"

[params]
favicon = "/favicon.ico"
